if(WIN32)
    set(USE_WIN32 ON)
    ADD_DEFINITIONS(-DUSE_WIN32)
else(WIN32)
    find_package(GTK2)
    if(GTK2_FOUND)
        set(HAVE_GTK2 ON)
        set(USE_GTK2 ON)
        ADD_DEFINITIONS(-DUSE_GTK2)
        include_directories(${GTK2_INCLUDE_DIRS})
    else(GTK2_FOUND)
        message(NOT FOUND GTK2)
    endif(GTK2_FOUND)
endif(WIN32)

find_package(MATHGL2)
if(MATHGL2_FOUND)
    include_directories(MATHGL2_INCLUDE_DIR)
endif()