#if(NOT DEFINED CMAKE_INSTALL_PREFIX)
#    if(UNIX)
#        set(CMAKE_INSTALL_PREFIX "/usr/Alchemy" CACHE PATH "Installation Directory")
#    elseif(WIN32)
#        set(CMAKE_INSTALL_PREFIX "D:/Alchemy" CACHE PATH "Installation Directory")
#    endif()
#endif()
#
## header files
#install(FILES  ${PROJECT_SOURCE_DIR}/modules/alchemy.h DESTINATION "${CMAKE_INSTALL_PREFIX}/include/")
#install(DIRECTORY ${PROJECT_SOURCE_DIR}/modules/util/ DESTINATION "${CMAKE_INSTALL_PREFIX}/include/util" FILES_MATCHING PATTERN "*.h")
#install(DIRECTORY ${PROJECT_SOURCE_DIR}/modules/core/ DESTINATION "${CMAKE_INSTALL_PREFIX}/include/core" FILES_MATCHING PATTERN "*.h")
#install(DIRECTORY ${PROJECT_SOURCE_DIR}/modules/gui/ DESTINATION "${CMAKE_INSTALL_PREFIX}/include/gui" FILES_MATCHING PATTERN "*.h")
#install(DIRECTORY ${PROJECT_SOURCE_DIR}/modules/imgproc/ DESTINATION "${CMAKE_INSTALL_PREFIX}/include/imgproc" FILES_MATCHING PATTERN "*.h")
#install(DIRECTORY ${PROJECT_SOURCE_DIR}/modules/math/ DESTINATION "${CMAKE_INSTALL_PREFIX}/include/math" FILES_MATCHING PATTERN "*.h")
#install(DIRECTORY ${PROJECT_SOURCE_DIR}/modules/nn/ DESTINATION "${CMAKE_INSTALL_PREFIX}/include/nn" FILES_MATCHING PATTERN "*.h")
